In [248]:
import pandas as pd

df = pd.read_csv('../data/survey_data.csv')
df

,idx,직급,소속,학력,근속년수,이직의사,조직문화평가_복지,조직문화평가_회의,조직문화평가_교육,조직문화평가_업무,...,2Q_업무몰입도평가_고객,2Q_업무몰입도평가_회의,2Q_업무몰입도평가_기술력,2Q_업무몰입도평가_소통,2Q_업무몰입도평가_보고,조직문화평가_100점,1Q_업무몰입도평가_100점,2Q_업무몰입도평가_100점,통합점수_평균,통합점수_전년대비증감
0,0,CL4,A그룹,학사,18,의사 있음,4.0,2.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,70.0,-2.5
1,1,CL3,A그룹,박사,12,의사 있음,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,64.0,NaN,64.0,-13.1
2,2,CL4,B그룹,학사,23,의사 없음,5.0,4.0,4.0,3.0,...,2.0,3.0,5.0,2.0,4.0,82.5,40.0,64.0,62.2,-0.9
3,3,CL4,H그룹,학사,21,의사 있음,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.4
4,4,CL2,D그룹,학사,3,의사 없음,2.0,2.0,4.0,3.0,...,2.0,3.0,1.0,4.0,3.0,60.0,64.0,52.0,58.7,-8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,445,CL4,H그룹,석사,16,의사 있음,5.0,4.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,77.5,64.0,NaN,70.8,-7.1
446,446,CL4,G그룹,학사,23,의사 없음,3.0,5.0,4.0,3.0,...,4.0,4.0,4.0,3.0,4.0,67.5,56.0,76.0,66.5,-2.9
447,447,CL4,F그룹,석사,13,의사 있음,2.0,2.0,2.0,3.0,...,3.0,3.0,4.0,3.0,1.0,55.0,72.0,56.0,61.0,2.9
448,448,CL2,F그룹,학사,2,의사 있음,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,1.0,4.0,NaN,68.0,56.0,62.0,-2.3
449,449,CL4,E그룹,학사,26,의사 있음,3.0,3.0,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,67.5,NaN,NaN,67.5,-2.3

In [249]:
df.fillna(0,inplace=True)

In [250]:
I_fresh  = ((df["근속년수"] >= 0)  & (df["근속년수"] < 3)).astype(int)
I_junior = ((df["근속년수"] >= 3)  & (df["근속년수"] < 10)).astype(int)
I_middle = ((df["근속년수"] >= 10) & (df["근속년수"] < 20)).astype(int)
I_senior = (df["근속년수"] >= 20).astype(int)

df = df.drop(columns='근속년수')
df["근속년수_구분"] = 1 * I_fresh + 2 * I_junior + 3 * I_middle + 4 * I_senior

df

,idx,직급,소속,학력,이직의사,조직문화평가_복지,조직문화평가_회의,조직문화평가_교육,조직문화평가_업무,조직문화평가_상사,...,2Q_업무몰입도평가_회의,2Q_업무몰입도평가_기술력,2Q_업무몰입도평가_소통,2Q_업무몰입도평가_보고,조직문화평가_100점,1Q_업무몰입도평가_100점,2Q_업무몰입도평가_100점,통합점수_평균,통합점수_전년대비증감,근속년수_구분
0,0,CL4,A그룹,학사,의사 있음,4.0,2.0,4.0,3.0,3.0,...,0.0,0.0,0.0,0.0,70.0,0.0,0.0,70.0,-2.5,3
1,1,CL3,A그룹,박사,의사 있음,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,64.0,0.0,64.0,-13.1,3
2,2,CL4,B그룹,학사,의사 없음,5.0,4.0,4.0,3.0,4.0,...,3.0,5.0,2.0,4.0,82.5,40.0,64.0,62.2,-0.9,4
3,3,CL4,H그룹,학사,의사 있음,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.4,4
4,4,CL2,D그룹,학사,의사 없음,2.0,2.0,4.0,3.0,3.0,...,3.0,1.0,4.0,3.0,60.0,64.0,52.0,58.7,-8.2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,445,CL4,H그룹,석사,의사 있음,5.0,4.0,4.0,3.0,3.0,...,0.0,0.0,0.0,0.0,77.5,64.0,0.0,70.8,-7.1,3
446,446,CL4,G그룹,학사,의사 없음,3.0,5.0,4.0,3.0,3.0,...,4.0,4.0,3.0,4.0,67.5,56.0,76.0,66.5,-2.9,4
447,447,CL4,F그룹,석사,의사 있음,2.0,2.0,2.0,3.0,3.0,...,3.0,4.0,3.0,1.0,55.0,72.0,56.0,61.0,2.9,3
448,448,CL2,F그룹,학사,의사 있음,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,1.0,4.0,0.0,68.0,56.0,62.0,-2.3,1
449,449,CL4,E그룹,학사,의사 있음,3.0,3.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,67.5,0.0,0.0,67.5,-2.3,4

In [251]:
CL_map = {'CL1' : 1 , 'CL2' : 2 ,  'CL3' : 3, 'CL4':4}
degree_map = {'고졸' : 1, '학사':2, '석사':2,'박사':3}

df['직급'] = df['직급'].map(CL_map)
df['학력'] = df['학력'].map(degree_map)
df

,idx,직급,소속,학력,이직의사,조직문화평가_복지,조직문화평가_회의,조직문화평가_교육,조직문화평가_업무,조직문화평가_상사,...,2Q_업무몰입도평가_회의,2Q_업무몰입도평가_기술력,2Q_업무몰입도평가_소통,2Q_업무몰입도평가_보고,조직문화평가_100점,1Q_업무몰입도평가_100점,2Q_업무몰입도평가_100점,통합점수_평균,통합점수_전년대비증감,근속년수_구분
0,0,4,A그룹,2,의사 있음,4.0,2.0,4.0,3.0,3.0,...,0.0,0.0,0.0,0.0,70.0,0.0,0.0,70.0,-2.5,3
1,1,3,A그룹,3,의사 있음,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,64.0,0.0,64.0,-13.1,3
2,2,4,B그룹,2,의사 없음,5.0,4.0,4.0,3.0,4.0,...,3.0,5.0,2.0,4.0,82.5,40.0,64.0,62.2,-0.9,4
3,3,4,H그룹,2,의사 있음,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.4,4
4,4,2,D그룹,2,의사 없음,2.0,2.0,4.0,3.0,3.0,...,3.0,1.0,4.0,3.0,60.0,64.0,52.0,58.7,-8.2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,445,4,H그룹,2,의사 있음,5.0,4.0,4.0,3.0,3.0,...,0.0,0.0,0.0,0.0,77.5,64.0,0.0,70.8,-7.1,3
446,446,4,G그룹,2,의사 없음,3.0,5.0,4.0,3.0,3.0,...,4.0,4.0,3.0,4.0,67.5,56.0,76.0,66.5,-2.9,4
447,447,4,F그룹,2,의사 있음,2.0,2.0,2.0,3.0,3.0,...,3.0,4.0,3.0,1.0,55.0,72.0,56.0,61.0,2.9,3
448,448,2,F그룹,2,의사 있음,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,1.0,4.0,0.0,68.0,56.0,62.0,-2.3,1
449,449,4,E그룹,2,의사 있음,3.0,3.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,67.5,0.0,0.0,67.5,-2.3,4

In [252]:
df = pd.get_dummies(df, columns=['소속'],drop_first=False)
df

,idx,직급,학력,이직의사,조직문화평가_복지,조직문화평가_회의,조직문화평가_교육,조직문화평가_업무,조직문화평가_상사,조직문화평가_부서,...,통합점수_전년대비증감,근속년수_구분,소속_A그룹,소속_B그룹,소속_C그룹,소속_D그룹,소속_E그룹,소속_F그룹,소속_G그룹,소속_H그룹
0,0,4,2,의사 있음,4.0,2.0,4.0,3.0,3.0,4.0,...,-2.5,3,True,False,False,False,False,False,False,False
1,1,3,3,의사 있음,0.0,0.0,0.0,0.0,0.0,0.0,...,-13.1,3,True,False,False,False,False,False,False,False
2,2,4,2,의사 없음,5.0,4.0,4.0,3.0,4.0,5.0,...,-0.9,4,False,True,False,False,False,False,False,False
3,3,4,2,의사 있음,0.0,0.0,0.0,0.0,0.0,0.0,...,-6.4,4,False,False,False,False,False,False,False,True
4,4,2,2,의사 없음,2.0,2.0,4.0,3.0,3.0,5.0,...,-8.2,2,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,445,4,2,의사 있음,5.0,4.0,4.0,3.0,3.0,3.0,...,-7.1,3,False,False,False,False,False,False,False,True
446,446,4,2,의사 없음,3.0,5.0,4.0,3.0,3.0,2.0,...,-2.9,4,False,False,False,False,False,False,True,False
447,447,4,2,의사 있음,2.0,2.0,2.0,3.0,3.0,3.0,...,2.9,3,False,False,False,False,False,True,False,False
448,448,2,2,의사 있음,0.0,0.0,0.0,0.0,0.0,0.0,...,-2.3,1,False,False,False,False,False,True,False,False
449,449,4,2,의사 있음,3.0,3.0,4.0,4.0,4.0,3.0,...,-2.3,4,False,False,False,False,True,False,False,False

In [253]:
status_map = {'의사 있음':1, '의사 없음':0}

df['이직의사'] = df['이직의사'].map(status_map)
df

,idx,직급,학력,이직의사,조직문화평가_복지,조직문화평가_회의,조직문화평가_교육,조직문화평가_업무,조직문화평가_상사,조직문화평가_부서,...,통합점수_전년대비증감,근속년수_구분,소속_A그룹,소속_B그룹,소속_C그룹,소속_D그룹,소속_E그룹,소속_F그룹,소속_G그룹,소속_H그룹
0,0,4,2,1,4.0,2.0,4.0,3.0,3.0,4.0,...,-2.5,3,True,False,False,False,False,False,False,False
1,1,3,3,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-13.1,3,True,False,False,False,False,False,False,False
2,2,4,2,0,5.0,4.0,4.0,3.0,4.0,5.0,...,-0.9,4,False,True,False,False,False,False,False,False
3,3,4,2,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-6.4,4,False,False,False,False,False,False,False,True
4,4,2,2,0,2.0,2.0,4.0,3.0,3.0,5.0,...,-8.2,2,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,445,4,2,1,5.0,4.0,4.0,3.0,3.0,3.0,...,-7.1,3,False,False,False,False,False,False,False,True
446,446,4,2,0,3.0,5.0,4.0,3.0,3.0,2.0,...,-2.9,4,False,False,False,False,False,False,True,False
447,447,4,2,1,2.0,2.0,2.0,3.0,3.0,3.0,...,2.9,3,False,False,False,False,False,True,False,False
448,448,2,2,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-2.3,1,False,False,False,False,False,True,False,False
449,449,4,2,1,3.0,3.0,4.0,4.0,4.0,3.0,...,-2.3,4,False,False,False,False,True,False,False,False

In [254]:
df.columns

Index(['idx', '직급', '학력', '이직의사', '조직문화평가_복지', '조직문화평가_회의', '조직문화평가_교육',
       '조직문화평가_업무', '조직문화평가_상사', '조직문화평가_부서', '조직문화평가_C레벨', '조직문화평가_동료',
       '1Q_업무몰입도평가_고객', '1Q_업무몰입도평가_회의', '1Q_업무몰입도평가_기술력', '1Q_업무몰입도평가_소통',
       '1Q_업무몰입도평가_보고', '2Q_업무몰입도평가_고객', '2Q_업무몰입도평가_회의', '2Q_업무몰입도평가_기술력',
       '2Q_업무몰입도평가_소통', '2Q_업무몰입도평가_보고', '조직문화평가_100점', '1Q_업무몰입도평가_100점',
       '2Q_업무몰입도평가_100점', '통합점수_평균', '통합점수_전년대비증감', '근속년수_구분', '소속_A그룹',
       '소속_B그룹', '소속_C그룹', '소속_D그룹', '소속_E그룹', '소속_F그룹', '소속_G그룹', '소속_H그룹'],
      dtype='object')

In [255]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

TRAIN_FEATURE_SVM = ['복지','회의','교육','업무','상사','동료']

df_selection = pd.DataFrame()
for item in TRAIN_FEATURE_SVM:
    df_selection[item] = df[f'조직문화평가_{item}']

df_selection['회의'] = df['1Q_업무몰입도평가_회의'] + df['2Q_업무몰입도평가_회의']
df_selection['업무'] = df['1Q_업무몰입도평가_고객'] + df['2Q_업무몰입도평가_고객'] + df['1Q_업무몰입도평가_기술력'] + df['2Q_업무몰입도평가_기술력']
df_selection['상사'] = df['1Q_업무몰입도평가_보고'] + df['2Q_업무몰입도평가_보고'] + df['1Q_업무몰입도평가_소통'] + df['2Q_업무몰입도평가_소통']

In [256]:
df_selection.columns
df_selection.dropna(axis=1)

      복지   회의   교육    업무    상사   동료
0    4.0  0.0  4.0   0.0   0.0  4.0
1    0.0  3.0  0.0   5.0   8.0  0.0
2    5.0  6.0  4.0  11.0   9.0  4.0
3    0.0  0.0  0.0   0.0   0.0  0.0
4    2.0  6.0  4.0  10.0  13.0  2.0
..   ...  ...  ...   ...   ...  ...
445  5.0  4.0  4.0   7.0   5.0  4.0
446  3.0  6.0  4.0  13.0  14.0  3.0
447  2.0  6.0  2.0  13.0  13.0  4.0
448  0.0  6.0  0.0  13.0  12.0  0.0
449  3.0  0.0  4.0   0.0   0.0  3.0

[450 rows x 6 columns]

In [257]:
X = df_selection[['복지', '회의', '교육', '업무', '상사', '동료']]
y = df['이직의사']

X_tn, X_te, y_tn, y_te = train_test_split(X,y,random_state=15)

std = StandardScaler()
std.fit(X_tn)
X_tn_std = std.transform(X_tn)
X_te_std = std.transform(X_te)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

tree_model = DecisionTreeClassifier(random_state=15,criterion='entropy',max_features=3)
logistic = LogisticRegression()
svm = SVC(kernel='linear',C=1, degree=4)
GNB = GaussianNB()

voting = VotingClassifier(
    estimators=[
    ('lm',logistic),
     ('gnb',GNB),
     ('svm',svm)
     ],
     voting='hard',
     weights=[1,1,1]
)

voting.fit(X_tn_std,y_tn)
tree_model.fit(X_tn_std,y_tn)

y_pred_voting = voting.predict(X_te_std)
y_pred_tree = tree_model.predict(X_te_std)
print(y_pred_voting)
print(y_pred_tree)

[1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 0]
[0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1
 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1
 1 1 0 1 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0
 0 0]

In [259]:
from sklearn.metrics import accuracy_score,classification_report

report = classification_report(y_te, y_pred_voting)
print('========Voting===========')
print(report)

report = classification_report(y_te, y_pred_tree)
print('========tree===========')
print(report)

tree_model.feature_importances_

========Voting===========
              precision    recall  f1-score   support

           0       0.71      0.24      0.36        50
           1       0.60      0.92      0.73        63

    accuracy                           0.62       113
   macro avg       0.66      0.58      0.54       113
weighted avg       0.65      0.62      0.57       113

========tree===========
              precision    recall  f1-score   support

           0       0.51      0.48      0.49        50
           1       0.61      0.63      0.62        63

    accuracy                           0.57       113
   macro avg       0.56      0.56      0.56       113
weighted avg       0.56      0.57      0.56       113

array([0.07346773, 0.26678031, 0.12164729, 0.21496864, 0.23603529,
       0.08710074])